server:
  port: 8092

spring:
  application:
    name: spring-boot-feign
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/